### ISSUE TITLE
Mongo connection issue

### ISSUE THREAD

**Issue by carcinogoy** [peavers-released/jackett-rss-processor#71]
Hi

I've just added this to my seedbox but can't get it to work using the docker-compose settings specified.

The logs for jackett-rss-processor are

```
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches WritableServerSelector. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:27017}, caused by {java.net.ConnectException: Connection refused}}]
        at com.mongodb.internal.connection.BaseCluster.createTimeoutException(BaseCluster.java:403) ~[mongodb-driver-core-4.0.5.jar:na]
        at com.mongodb.internal.connection.BaseCluster.handleServerSelectionRequest(BaseCluster.java:311) ~[mongodb-driver-core-4.0.5.jar:na]
        at com.mongodb.internal.connection.BaseCluster.access$800(BaseCluster.java:62) ~[mongodb-driver-core-4.0.5.jar:na]
        at com.mongodb.internal.connection.BaseCluster$WaitQueueHandler.run(BaseCluster.java:474) ~[mongodb-driver-core-4.0.5.jar:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

And there are no new events in jackett-rss-mongo.

My docker-compose.yml is as follows

```
jackett-rss-processor:
    image: peavers/jackett-rss-processor:latest
    container_name: jackett-rss-processor
    restart: unless-stopped
    ports:
      - 8040:8080
    volumes:
      - /disk1/blackhole:/watched
    depends_on:
      - jackett
      - jackett-rss-mongo
    logging:
      options:
        max-size: "2m"
        max-file: "5"

jackett-rss-mongo:
    image: mongo:latest
    container_name: jackett-rss-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    logging:
      options:
        max-size: "2m"
        max-file: "5"

volumes:
  mongo-data:
```

Am I missing something?

**Comment by carcinogoy** [comment]
Extra error I saw in logs
```
org.springframework.core.codec.DecodingException: Could not unmarshal XML to class space.forloop.rss.domain.jackett.JacketRoot; nested exception is javax.xml.bind.UnmarshalException
 - with linked exception:
[com.sun.istack.SAXParseException2; lineNumber: 2; columnNumber: 51; unexpected element (uri:"", local:"error"). Expected elements are <{}rss>]
        at org.springframework.http.codec.xml.Jaxb2XmlDecoder.unmarshal(Jaxb2XmlDecoder.java:222) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        |_ checkpoint ⇢ Body from GET http://jackett:9117/api/v2.0/indexers/REDACTED/results/torznab/api?apikey=REDACTED&t=search&cat=&q= [DefaultClientResponse]
        |_ checkpoint ⇢ Handler space.forloop.rss.controllers.FeedController#save(Feed) [DispatcherHandler]
        |_ checkpoint ⇢ space.forloop.rss.filters.ResourceWebFilter [DefaultWebFilterChain]
        |_ checkpoint ⇢ HTTP POST "/api/feeds" [ExceptionHandlingWebHandler]
```

**Comment by peavers** [comment]
Hi, 

Do you have any network settings in the rest of your docker-compose file?

**Comment by carcinogoy** [comment]
I have network-mode: host for a deluge container

```
version: '3.7'
services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=000 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /home/seedbox/deluge/config:/config
      - /disk1/downloading:/downloading
      - /disk1/completed:/completed
      - /disk1/blackhole:/watched
    restart: unless-stopped

  jackett-rss-processor:
    image: peavers/jackett-rss-processor:latest
    container_name: jackett-rss-processor
    restart: unless-stopped
    ports:
      - 8040:8080
    volumes:
      - /disk1/blackhole:/watched
    depends_on:
      - jackett
      - jackett-rss-mongo
    logging:
      options:
        max-size: "2m"
        max-file: "5"

  jackett-rss-mongo:
    image: mongo:latest
    container_name: jackett-rss-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    logging:
      options:
        max-size: "2m"
        max-file: "5"

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - /disk1/completed:/completed
      - /home/seedbox/unpackerr:/etc/unpackerr
    restart: always

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    ports:
      - 9117:9117
    volumes:
      - /home/seedbox/jackett:/config
      - /etc/timezone:/etc/timezone:ro
    restart: on-failure

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=000
    ports:
      - 8989:8989
    volumes:
      - /home/seedbox/sonarr/config:/config
      - /disk1/completed:/completed
      - /disk1/unpacked:/unpacked
      - /disk1/media:/media
      - /etc/timezone:/etc/timezone:ro
    restart: on-failure

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=000
    ports:
      - 7878:7878
    volumes:
      - /home/seedbox/radarr:/config
      - /disk1/completed:/completed
      - /disk1/unpacked:/unpacked
      - /disk1/media:/media
      - /etc/timezone:/etc/timezone:ro
    restart: on-failure

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    ports:
      - 8096:8096
    volumes:
      - /home/seedbox/jellyfin/config:/config
      - /disk1/media:/media
      - /etc/timezone:/etc/timezone:ro
    restart: on-failure

volumes:
  mongo-data:
```

I've tried with nothing running except the yml you specified in the readme.
